"""add oemqa family

Revision ID: b7ab80020774
Revises: a23713521472
Create Date: 2025-08-07 07:57:48.412849+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ab80020774'
down_revision = 'a23713521472'
branch_labels = None
depends_on = None


def upgrade() -> None:
    add_oemqa_family()


def add_oemqa_family():
    op.execute("ALTER TYPE familyname ADD VALUE IF NOT EXISTS 'oemqa'")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
